name: Check

# Controls when the action will run.
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    name: Check
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - name: Update sponsors
        run: npm run update-sponsors
        env:
          GITHUB_TOKEN: ${{ secrets.SPONSOR_TOKEN }}
      - name: Commit changes
        run: bash ./commit.sh
